os: linux
dist: xenial
language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

jobs:
  include:
    - php: 7.4
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.3
      env: WP_VERSION=latest

install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require "squizlabs/php_codesniffer=*"
      composer global require dealerdirect/phpcodesniffer-composer-installer
      composer global require wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
